// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SisConsultaMVC.Data;

namespace SisConsultaMVC.Migrations
{
    [DbContext(typeof(SisConsultaContext))]
    partial class SisConsultaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SisConsultaMVC.Models.Consulta", b =>
                {
                    b.Property<int>("ConsultaID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataConsulta");

                    b.Property<int>("MedicoID");

                    b.Property<int>("PacienteID");

                    b.HasKey("ConsultaID");

                    b.HasIndex("MedicoID");

                    b.HasIndex("PacienteID");

                    b.ToTable("Consulta");
                });

            modelBuilder.Entity("SisConsultaMVC.Models.Medico", b =>
                {
                    b.Property<int>("MedicoID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("MedicoID");

                    b.ToTable("Medico");
                });

            modelBuilder.Entity("SisConsultaMVC.Models.Paciente", b =>
                {
                    b.Property<int>("PacienteID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro");

                    b.Property<string>("Cidade");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14);

                    b.Property<string>("Email");

                    b.Property<string>("NomePaciente")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("NumTelefone");

                    b.Property<int?>("Numero");

                    b.Property<string>("Rua");

                    b.HasKey("PacienteID");

                    b.ToTable("Paciente");
                });

            modelBuilder.Entity("SisConsultaMVC.Models.Consulta", b =>
                {
                    b.HasOne("SisConsultaMVC.Models.Medico", "Medico")
                        .WithMany("Consultas")
                        .HasForeignKey("MedicoID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SisConsultaMVC.Models.Paciente", "Paciente")
                        .WithMany("Consultas")
                        .HasForeignKey("PacienteID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
